// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class cancelnonnullofpropertyofannoucement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cancelnonnullofpropertyofannoucement));
        
        string IMigrationMetadata.Id
        {
            get { return "201605130158484_cancel non-null of property of annoucement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
