// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removedescriptioninorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedescriptioninorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201605132304375_remove description in order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
