// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removeuserIdbecausewehavealreadyuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeuserIdbecausewehavealreadyuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201605131855212_remove userId (because we have already user)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
