// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changetypeofquantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetypeofquantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201605131728574_change type of quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
